version: '3'
services:
  kamailio:
    container_name: kamailio
    hostname: kamailio.local
    build: images/kamailio
    image: telephoneorg/kamailio:${DOCKER_TAG:-latest}
    environment:
      KAMAILIO_LOG_LEVEL: info
      KAMAILIO_ENABLE_ROLES: websockets,message,presence_query,presence_notify_sync,registrar_sync
      RABBITMQ_HOSTS: rabbitmq.local
    ports:
    - "5060-5061:5060-5061"
    - "5060:5060/udp"
    - "5064-5065:5064-5065"
    - "5064-5065:5064-5065/udp"
    - "7000-7001:7000-7001"
    - "7000:7000/udp"
    cap_add:
    - IPC_LOCK
    - NET_ADMIN
    - NET_RAW
    - NET_BROADCAST
    - SYS_NICE
    - SYS_RESOURCE
    networks:
      local:
        aliases:
        - kamailio.local
    depends_on:
      rabbitmq:
        condition: service_healthy
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq.local
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: change-me
    image: telephoneorg/rabbitmq:latest
    networks:
      local:
        aliases:
        - rabbitmq.local
networks:
local:
