version: '3'
services:
  kamailio:
    container_name: kamailio
    hostname: kamailio.proxy
    build: images/kamailio
    image: telephoneorg/kamailio:${DOCKER_TAG:-latest}
    environment:
      KAMAILIO_LOG_LEVEL: info
      KAMAILIO_ENABLE_ROLES: websockets,message,presence_query,presence_notify_sync,registrar_sync
      RABBITMQ_HOSTS: rabbitmq.proxy
    ports:
    - "5060-5061:5060-5061"
    - "5060:5060/udp"
    - "5064-5065:5064-5065"
    - "5064-5065:5064-5065/udp"
    - "7000-7001:7000-7001"
    - "7000:7000/udp"
    cap_add:
    - IPC_LOCK
    - NET_ADMIN
    - NET_RAW
    - NET_BROADCAST
    - SYS_NICE
    - SYS_RESOURCE
    networks:
      proxy:
        aliases:
        - kamailio.proxy
networks:
   proxy:
