version: '3'
services:
   modoboa:
    image: flavioaiello/modoboa
    environment:
      - ADMIN_PASSWORD=changeme
    ports:
      - 5000:5000
      - 8081:8081
    volumes:
      - /tmp/modoboa:/mailserver
    restart: always
