version: '3'
services:
  kazoo:
    container_name: kazoo
    hostname: kazoo.local
    build:
      context: images/kazoo
    image: 2600hz/kazoo:${DOCKER_TAG:-latest}
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: change-me
      RABBITMQ_HOST: rabbitmq.local
      COUCHDB_HOST: couchdb.local
      KAZOO_LOG_LEVEL: info
    ports:
    - "5555:5555"
    - "8000:8000"
    - "19025:19025"
    - "24517:24517"
    tmpfs:
    - /tmp
    networks:
      local:
        aliases:
        - kazoo.local
    cap_add:
    - SYS_NICE
    - SYS_RESOURCE
    depends_on:
      rabbitmq:
        condition: service_healthy
      couchdb:
        condition: service_healthy
  rabbitmq:
    service_name: rabbitmq_rabbitmq
    hostname: rabbitmq.local
    image: telephoneorg/rabbitmq:latest
    environment:
      ERLANG_HOSTNAME: long
      ERLANG_COOKIE: change-me
    tmpfs:
    - /var/lib/rabbitmq/mnesia
    networks:
      local:
        aliases:
        - rabbitmq.local
  couchdb:
    service_name: couchdb_couchdb
    hostname: couchdb.local
    image: telephoneorg/couchdb:latest
    environment:
      COUCHDB_DEV_INIT: 'true'
      ERLANG_COOKIE: change-me
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
      COUCHDB_SHARDS: '1'
      COUCHDB_LOG_LEVEL: info
    ports:
    - "5984:5984"
    - "5986:5986"
    networks:
      local:
        aliases:
        - couchdb.local
networks:
   local:
