version: '3.3'

#
# ─── SERVICES ───────────────────────────────────────────────────────────────────
#

services:

  #
  # SERVICE: Traefik (proxy)
  # 

  proxy:
    image:      traefik
    restart:    always

    hostname:   '${HOST_NAME:-traefik}'
    domainname: '${DOMAIN_NAME:-local}'
    
    configs:
      - source: toml
        target: /etc/traefik/traefik.toml
    
    volumes:
      - acme:/etc/traefik/acme                    # ACME TLS persistence
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket
    
    networks:
      traefik:
    
    ports:
       - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    
    deploy:
      mode: global

      placement:
        constraints:
          - node.role == manager

      update_config:
        parallelism: 1
        delay: 10s

      labels:
        traefik.enable:               'true'
        traefik.port:                 '${PORT}' # Backend management web server ports
        traefik.protocol:             'http'    # Backend management web server protocols
        traefik.backend:              'proxy'   # Docker Stack backend name
        traefik.frontend.rule:        'Host:${HOST_NAME}.${DOMAIN_NAME}'
        traefik.frontend.entryPoints: '${TRAEFIK_ENTRY_POINTS:-http,https}'

#
# ─── VOLUMES ────────────────────────────────────────────────────────────────────
#

volumes:
  acme: # ACME TLS persistence

#
# ─── NETWORKS ───────────────────────────────────────────────────────────────────
#

networks:
  traefik:
    driver: overlay
    external:
      name: ${TRAEFIK_NETWORK:-traefik}

#
# ─── CONFIGS ────────────────────────────────────────────────────────────────────
#

configs:
  toml:
    external: 
       name: ${TRAEFIK_TOML:-traefik_toml}
