version: "3.3"
services:
  traefik:
    image: traefik
    command: --web \
      --docker \
      --docker.swarmmode \
      --docker.domain=host1.t-factor.co.uk \
      --docker.watch \
      --logLevel=DEBUG
    networks:
      - proxy
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik.toml
    deploy:
      placement:
        constraints: [node.role==manager]
networks:
   proxy:
