version: '3'
services:
  couchdb:
    container_name: couchdb
    hostname: couchdb.local
    build:
      context: images/couchdb
      args:
        COUCHDB_VERSION: 2.1.1
        COUCHDB_ADMIN_VERSION: 0.1.0
    image: telephoneorg/couchdb:${DOCKER_TAG:-latest}
    environment:
      COUCHDB_DEV_INIT: 'true'
      COUCHDB_ADMIN_USER: admin
      COUCHDB_ADMIN_PASS: secret
      ERLANG_COOKIE: change-me
    ports:
    - "5984:5984"
    - "5986:5986"
    networks:
      local:
        aliases:
        - couchdb.local
    cap_add:
    - SYS_NICE
    - SYS_RESOURCE
networks:
  local:
